DROP DATABASE riot;
CREATE DATABASE riot;
USE riot;
CREATE TABLE `knex_migrations` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NULL DEFAULT NULL,
	`batch` INT(11) NULL DEFAULT NULL,
	`migration_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=INNODB;
CREATE TABLE `knex_migrations_lock` (
	`index` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`is_locked` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`index`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;