declare module 'abraxas' {
  export class Client {
    static connect(options: any, onConnect?: any): any;
    constructor(options: any);
    options: any;
    connections: any;
    addListener(type: any, listener: any): any;
    askForWork(): void;
    disconnect(): void;
    dispatchWorker(job: any, socket: any): void;
    echo(options: any, data: any, onComplete: any): any;
    emit(type: any, args: any): any;
    endWork(jobid: any): void;
    eventNames(): any;
    forgetAllWorkers(): void;
    getConnectedServers(): any;
    getConnection(timeout: any, callback: any): void;
    getMaxListeners(): any;
    getStatus(jobid: any, options: any, onComplete: any): void;
    isRegistered(func: any): any;
    listenerCount(type: any): any;
    listeners(type: any): any;
    maxqueue(func: any, maxsize: any, onComplete: any): any;
    off(type: any, listener: any): any;
    on(type: any, listener: any): any;
    once(type: any, listener: any): any;
    prependListener(type: any, listener: any): any;
    prependOnceListener(type: any, listener: any): any;
    rawListeners(type: any): any;
    registerWorker(func: any, options: any, handler: any): any;
    registerWorkerStream(func: any, options: any, handler: any): any;
    removeAllListeners(type: any, ...args: any[]): any;
    removeListener(type: any, listener: any): any;
    setClientId(id: any): void;
    setMaxListeners(n: any): any;
    shutdown(graceful: any, onComplete: any): any;
    startTask(callback: any, options: any, next: any): any;
    startWork(jobid: any): void;
    status(options: any, onComplete: any): any;
    submitJob(func: any, options: any, data: any, onComplete: any): any;
    submitJobAt(func: any, time: any, options: any, data: any, onComplete: any): any;
    submitJobBg(func: any, options: any, data: any, onComplete: any): any;
    submitJobSched(func: any, time: any, options: any, data: any, onComplete: any): any;
    unregisterWorker(func: any): void;
    workers(options: any, onComplete: any): any;
  }
  export class Error {
    static Connect(msg: any): void;
    static ConnectTimeout(): void;
    static Emitter(msg: any): void;
    static JobException(name: any, jobid: any, payload: any): void;
    static JobFail(name: any, jobid: any): void;
    static NoStreaming(): void;
    static Parser(msg: any): void;
    static Receive(message: any): void;
    static ResponseTimeout(): void;
    static Server(code: any, message: any, err: any): void;
    static Socket(msg: any): void;
    static SubmitTimeout(): void;
    static trace(constructor: any): any;
    constructor(msg: any, props: any);
    withError(error: any): any;
  }
  export class Server {
    static listen(options: any, callback?: any): any;
    constructor(options: any);
    options: any;
    socket: any;
    clients: any;
    clientMaxId: any;
    workers: any;
    workersCount: any;
    jobs: any;
    acceptConnection(socket: any): void;
    addListener(type: any, listener: any): any;
    addWorker(func: any, client: any, options: any): void;
    emit(type: any, args: any): any;
    eventNames(): any;
    getMaxListeners(): any;
    getStatus(jobid: any, client: any): void;
    grabJob(client: any, unique: any): any;
    listenerCount(type: any): any;
    listeners(type: any): any;
    off(type: any, listener: any): any;
    on(type: any, listener: any): any;
    once(type: any, listener: any): any;
    prependListener(type: any, listener: any): any;
    prependOnceListener(type: any, listener: any): any;
    rawListeners(type: any): any;
    recordDisconnect(client: any): void;
    removeAllListeners(type: any, ...args: any[]): any;
    removeAllWorkers(client: any): void;
    removeListener(type: any, listener: any): any;
    removeWorker(func: any, client: any): void;
    setMaxListeners(n: any): any;
    shutdown(): void;
    submitJob(args: any): void;
    updateStatus(client: any, jobid: any, complete: any, total: any): void;
    wakeWorkers(): void;
    withJob(client: any, jobid: any, callback: any, nojobcallback: any): any;
    workComplete(client: any, jobid: any, body: any): void;
    workData(client: any, jobid: any, body: any): void;
    workException(client: any, jobid: any, body: any): void;
    workFail(client: any, jobid: any, body: any): void;
    workWarning(client: any, jobid: any, body: any): void;
  }
}
